<?php
/**
 * @file cguweb.install
 * Install, update and uninstall functions.
 */

/**
 * Implements hook_install().
 */
function cguweb_install() {
  // Set the default theme.
  _cguweb_set_up_theme();
}

/**
 * Set the default theme.
 */
function _cguweb_set_up_theme() {
  $theme = 'responsive_bartik';
  theme_enable(array($theme));
  variable_set('theme_default', $theme);
  theme_disable(array('bartik'));
}
